# Create and specify POD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg
      commit: bggdbpod
  template:
    metadata: 
      name: bggdbpod
      namespace: bggns
      labels:
        app: bgg
        commit: bggdbpod
    spec:
      containers:
      - name: bggdbpod-container
        image:  stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: bggdb-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggdb-svc
spec:
  type: ClusterIP
  selector: 
    app: bgg
    commit: bggdbpod
  ports:
  - port: 3306 
    targetPort: bggdb-port 